on:
  push:
    branches:
    - master
env:
  majorVersion: 5.1.2
  minorVersion: $[counter('minorVersion', 1)]
  ffmpegVersion: "$majorVersion.$minorVersion"
jobs:
  setup:
    name: Build Variables
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set Build Name
      run: echo "##vso[build.updatebuildnumber]$ffmpegVersion"
      shell: bash
  ffmpeg_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: '1'
    - name: Build
      run: win-x64/build.sh
      shell: bash
    - name: Publish FFmpeg
      uses: actions/upload-artifact@v2
      with:
        path: win-x64/output
        name: ffmpeg-win-x64
                    